server:
  port: 80


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yyy?useUnicode=true&amp;characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: root
